### ISSUE TITLE
instantFace analysis provider cuda error

### ISSUE THREAD

**Issue by frankchieng** [cubiq/ComfyUI_InstantID#60]
After running a couple of days,a new cuda problem exists as below,idk if the pytorch cache memory is full or cuda initializing problem
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/130369523/0eb38980-5551-4f62-9d3d-f37b48972822)
anyone has a clue?

**Comment by cubiq** [comment]
post the full backtrace please

**Comment by frankchieng** [comment]
> post the full backtrace please

problem solved,cloud server bug, pytorch can't tell where is cuda available, after i change another machine,it worked again
